### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by Kera73** [aalex94/Csapat_3#26]
Make a Class in C#, let the name: Login_Screen
> [!IMPORTANT]
>No input data, only output

Design the login screen
Class has two properties,  User_name and Password

**Comment by SziliCs** [comment]
Hello, I have encountered a problem. I am not able to create a pull request from my branch to the main branch.
Have you disabled creating pull requests to the main branch?

**Comment by SziliCs** [comment]
I will continue my work in a separate branch until this problem is solved.
Please give me a feedback if I am allowed to create a pull request.

**Comment by SziliCs** [comment]
I have just finished the work with designing the login screen.
Send me a notificiation when I can merge my work with the main branch.

**Comment by Kera73** [comment]
I didn't disabled pull requests, but try create to the master branch, not to the main.

**Comment by SziliCs** [comment]
Thank you, I created the pull request to the master branch.
Please take a look on it and write to me if there's anything to improve on the task.
